version: '3.8'
services:
  client:
    build: ./frontend
    ports:
      - "3000:3000"

  server:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/app/db/messages.db
